services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\Deepl\Base\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model'

  WebVision\Deepl\Base\EventListener\ProvideDefaultTypo3LocalizationModesEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'deepl-base/determine-default-typo3-localization-modes'
        event: WebVision\Deepl\Base\Event\GetLocalizationModesEvent

  WebVision\Deepl\Base\EventListener\PrepareLocalizationProcessDataHandlerCommandMapForTypo3LocalizationModes:
    tags:
      - name: 'event.listener'
        identifier: 'deepl-base/process-default-typo3-localization-modes'
        event: WebVision\Deepl\Base\Event\LocalizationProcessPrepareDataHandlerCommandMapEvent

  WebVision\Deepl\Base\EventListener\DefaultTranslationDropdownEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'deepl-base/default-translation'
        event: WebVision\Deepl\Base\Event\ViewHelpers\ModifyInjectVariablesViewHelperEvent
